# Generated by Django 3.2.25 on 2026-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20260525_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('quoted', 'Quoted'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('waiting_client', 'Waiting for Client'), ('review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=30),
        ),
    ]
