# Generated by Django 3.2.25 on 2026-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20260606_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='is_read_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='is_read_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
